variable "ENV" {}
variable "COMPONENT" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE_COUNT" {}
variable "NEXUS_USER" {}
variable "NEXUS_PASS" {}
variable "PORT" {}
variable "IS_PRIVATE_LB" {}
variable "APP_VERSION" {}
variable "LB_RULE_PRIORITY" {}
